import {
  PORTFOLIO_DISPLAY,
  BOARD_DENSITY,
  TABLE_DENSITY,
  BOARD_SORT_BY,
  STATUS,
} from "./constants";

// Hard-coded for now

export const LAST_PORTFOLIO_DISPLAY = PORTFOLIO_DISPLAY.TABLE.name;

// Dashboard
export const IS_CARD_COLORS_ON = true;
export const LAST_BOARD_DENSITY = BOARD_DENSITY.COMPACT.name;
export const LAST_BOARD_COLUMN_FILTER = [
  { status: "Rejected", isActive: false, isExpanded: false },
  { status: "Wishlist", isActive: false, isExpanded: false },
  { status: "Applied", isActive: true, isExpanded: false },
  { status: "Phone Screen", isActive: false, isExpanded: false },
  { status: "Interview", isActive: true, isExpanded: false },
  { status: "Offer", isActive: true, isExpanded: false },
];
export const LAST_BOARD_SORT_PROPERTY = BOARD_SORT_BY.LAST_UPDATE.property;
export const LAST_BOARD_IS_SORT_ASCENDING =
  BOARD_SORT_BY.LAST_UPDATE.isDefaultAscending;

// Table
export const LAST_TABLE_DENSITY = TABLE_DENSITY.COMFORTABLE.name;
export const LAST_TABLE_COLUMN_FILTER = [
  {
    name: "Date Created",
    property: "dateCreated",
    isDate: true,
    isActive: false,
  },
  {
    name: "Application Date",
    property: "applyDate",
    isDate: true,
    isActive: true,
  },
  { name: "Color", property: "color", isActive: false },
  { name: "Company", property: "company", isActive: true },
  { name: "Job Title", property: "jobTitle", isActive: true },
  { name: "Status", property: "status", isActive: true },
  { name: "URL", property: "url", isActive: true },
  { name: "Notes", property: "notes", isActive: false },
  {
    name: "Interview/Deadline",
    property: "deadlineDate",
    isDate: true,
    isActive: true,
  },
  {
    name: "Last Update",
    property: "lastUpdate",
    isDate: true,
    isActive: false,
  },
];
export const LAST_TABLE_SORT_PROPERTY = "company";
export const LAST_TABLE_IS_SORT_ASCENDING = true;

export const fakeEntries = [
  {
    id: 1,
    dateCreated: Date.now(),
    lastUpdate: Date.now(),
    color: "darkorchid",
    isStarred: false,
    company: "Facebook",
    domain: "google.com",
    logo: "https://logo.clearbit.com/facebook.com",
    jobTitle: "Software Engineer",
    applyDate: "2020-01-01",
    deadlineDate: "",
    status: STATUS.APPLIED,
    url: "",
    notes: "",
  },
  {
    id: 2,
    dateCreated: Date.now(),
    lastUpdate: Date.now(),
    color: "chocolate",
    isStarred: true,
    company: "Apple",
    domain: "google.com",
    logo: "https://logo.clearbit.com/apple.com",
    jobTitle: "Mechanical Engineer Intern - Cupertino, California",
    applyDate: "2020-05-03",
    deadlineDate: "2020-01-01",
    status: STATUS.APPLIED,
    url: "https://apple.com",
    notes:
      "kjdasfnjasnvsa o jsdkfsa\njsdav inus oufjuh oudsofjof sd\nAnother line",
  },
  {
    id: 3,
    dateCreated: Date.now(),
    lastUpdate: Date.now(),
    color: "navy",
    isStarred: true,
    company: "Doordash",
    domain: "google.com",
    logo: "https://logo.clearbit.com/doordash.com",
    jobTitle: "Software Engineer Intern",
    applyDate: "2020-01-01",
    deadlineDate: "2020-01-01",
    status: STATUS.INTERVIEW,
    url: "",
    notes: "siufha uafoidjiof oufdhsauofdj oqhwfw",
  },
  {
    id: 4,
    dateCreated: Date.now(),
    lastUpdate: Date.now(),
    color: "seagreen",
    isStarred: false,
    company: "Facebook",
    domain: "google.com",
    logo: "https://logo.clearbit.com/facebook.com",
    jobTitle: "Software Engineer II",
    applyDate: "2020-01-01",
    deadlineDate: "",
    status: STATUS.APPLIED,
    url: "",
    notes: "",
  },
  {
    id: 5,
    dateCreated: Date.now(),
    lastUpdate: Date.now(),
    color: "darkgreen",
    isStarred: true,
    company: "Apple",
    domain: "google.com",
    logo: "https://logo.clearbit.com/apple.com",
    jobTitle: "Mechanical Engineer Intern - Cupertino, California",
    applyDate: "2020-01-01",
    deadlineDate: "2020-01-01",
    status: STATUS.APPLIED,
    url: "https://apple.com",
    notes: "awiufwb\n\n\n\nsfwsdhbfsi",
  },
  {
    id: 6,
    dateCreated: Date.now(),
    lastUpdate: Date.now(),
    color: "indianred",
    isStarred: true,
    company: "Doordash",
    domain: "google.com",
    logo: "https://logo.clearbit.com/doordash.com",
    jobTitle: "Software Engineer Intern",
    applyDate: "2020-01-01",
    deadlineDate: "2020-01-01",
    status: STATUS.OFFER,
    url: "https://doordash.com",
    notes: "siufha uafoidjiof oufdhsauofdj oqhwfw",
  },
  {
    id: 7,
    dateCreated: Date.now(),
    lastUpdate: Date.now(),
    color: "darkcyan",
    isStarred: false,
    company: "Facebook",
    domain: "google.com",
    logo: "https://logo.clearbit.com/facebook.com",
    jobTitle: "Software Engineer",
    applyDate: "2020-01-01",
    deadlineDate: "",
    status: STATUS.APPLIED,
    url: "",
    notes: "sdjk dsaiiuh\nsdui",
  },
  {
    id: 8,
    dateCreated: Date.now(),
    lastUpdate: Date.now(),
    color: "mediumorchid",
    isStarred: false,
    company: "Microsoft",
    domain: "google.com",
    logo: "https://logo.clearbit.com/microsoft.com",
    jobTitle: "QA Engineer",
    applyDate: "2020-01-01",
    deadlineDate: "",
    status: STATUS.INTERVIEW,
    url: "https://microsoft.com",
    notes: "usf iosoidsoiaoi dsdsoa oiuh iuweq w ef",
  },
  {
    id: 9,
    dateCreated: Date.now(),
    lastUpdate: Date.now(),
    color: "coral",
    isStarred: false,
    company: "Oracle",
    domain: "oracle.com",
    logo: "https://logo.clearbit.com/oracle.com",
    jobTitle: "QA Engineer II",
    applyDate: "2020-01-01",
    deadlineDate: "",
    status: STATUS.OFFER,
    url: "",
    notes: "usf sfs wdfs dsef",
  },
  {
    id: 10,
    dateCreated: Date.now(),
    lastUpdate: Date.now(),
    color: "slateblue",
    isStarred: true,
    company: "Salesforce",
    domain: "salesforce.com",
    logo: "https://logo.clearbit.com/salesforce.com",
    jobTitle: "Data Analyst",
    applyDate: "2020-01-01",
    deadlineDate: "2020-01-01",
    status: STATUS.INTERVIEW,
    url: "https://salesforce.com",
    notes: "usf sfs wdfs dsef",
  },
  {
    id: 11,
    dateCreated: Date.now(),
    lastUpdate: Date.now(),
    color: "navy",
    isStarred: false,
    company: "React",
    domain: "google.com",
    logo: "https://logo.clearbit.com/reactjs.org",
    jobTitle: "Software Engineer III",
    applyDate: "2020-01-01",
    deadlineDate: "2020-11-22",
    status: STATUS.APPLIED,
    url: "",
    notes: "",
  },
  {
    id: 12,
    dateCreated: Date.now(),
    lastUpdate: Date.now(),
    color: "mediumorchid",
    isStarred: false,
    company: "Microsoft",
    domain: "google.com",
    logo: "https://logo.clearbit.com/microsoft.com",
    jobTitle: "QA Engineer",
    applyDate: "2020-01-01",
    deadlineDate: "",
    status: STATUS.INTERVIEW,
    url: "https://microsoft.com",
    notes: "usf iosoidsoiaoi dsdsoa oiuh iuweq w ef",
  },
  {
    id: 13,
    dateCreated: Date.now(),
    lastUpdate: Date.now(),
    color: "coral",
    isStarred: false,
    company: "Oracle",
    domain: "oracle.com",
    logo: "https://logo.clearbit.com/oracle.com",
    jobTitle: "QA Engineer II",
    applyDate: "2020-01-01",
    deadlineDate: "",
    status: STATUS.OFFER,
    url: "",
    notes: "usf sfs wdfs dsef",
  },
  {
    id: 14,
    dateCreated: Date.now(),
    lastUpdate: Date.now(),
    color: "slateblue",
    isStarred: true,
    company: "Salesforce",
    domain: "salesforce.com",
    logo: "https://logo.clearbit.com/salesforce.com",
    jobTitle: "Data Analyst",
    applyDate: "2020-01-01",
    deadlineDate: "2020-01-01",
    status: STATUS.INTERVIEW,
    url: "https://salesforce.com",
    notes: "usf sfs wdfs dsef",
  },
  {
    id: 15,
    dateCreated: Date.now(),
    lastUpdate: Date.now(),
    color: "navy",
    isStarred: false,
    company: "React",
    domain: "google.com",
    logo: "https://logo.clearbit.com/reactjs.org",
    jobTitle: "Software Engineer III",
    applyDate: "2020-01-01",
    deadlineDate: "2020-11-22",
    status: STATUS.APPLIED,
    url: "",
    notes: "",
  },
  {
    id: 16,
    dateCreated: Date.now(),
    lastUpdate: Date.now(),
    color: "slateblue",
    isStarred: true,
    company: "Salesforce",
    domain: "salesforce.com",
    logo: "https://logo.clearbit.com/salesforce.com",
    jobTitle: "Data Analyst",
    applyDate: "2020-01-01",
    deadlineDate: "2020-01-01",
    status: STATUS.INTERVIEW,
    url: "https://salesforce.com",
    notes: "usf sfs wdfs dsef",
  },
  {
    id: 17,
    dateCreated: Date.now(),
    lastUpdate: Date.now(),
    color: "navy",
    isStarred: false,
    company: "React",
    domain: "google.com",
    logo: "https://logo.clearbit.com/reactjs.org",
    jobTitle: "Software Engineer III",
    applyDate: "2020-01-01",
    deadlineDate: "2020-11-22",
    status: STATUS.APPLIED,
    url: "",
    notes: "",
  },
  {
    id: 18,
    dateCreated: Date.now(),
    lastUpdate: Date.now(),
    color: "mediumorchid",
    isStarred: false,
    company: "Microsoft",
    domain: "google.com",
    logo: "https://logo.clearbit.com/microsoft.com",
    jobTitle: "QA Engineer",
    applyDate: "2020-01-01",
    deadlineDate: "",
    status: STATUS.INTERVIEW,
    url: "https://microsoft.com",
    notes: "usf iosoidsoiaoi dsdsoa oiuh iuweq w ef",
  },
  {
    id: 19,
    dateCreated: Date.now(),
    lastUpdate: Date.now(),
    color: "coral",
    isStarred: false,
    company: "Oracle",
    domain: "oracle.com",
    logo: "https://logo.clearbit.com/oracle.com",
    jobTitle: "QA Engineer II",
    applyDate: "2020-01-01",
    deadlineDate: "",
    status: STATUS.OFFER,
    url: "",
    notes: "usf sfs wdfs dsef",
  },
  {
    id: 20,
    dateCreated: Date.now(),
    lastUpdate: Date.now(),
    color: "slateblue",
    isStarred: true,
    company: "Salesforce",
    domain: "salesforce.com",
    logo: "https://logo.clearbit.com/salesforce.com",
    jobTitle: "Data Analyst",
    applyDate: "2020-01-01",
    deadlineDate: "2020-01-01",
    status: STATUS.INTERVIEW,
    url: "https://salesforce.com",
    notes: "usf sfs wdfs dsef",
  },
  {
    id: 21,
    dateCreated: Date.now(),
    lastUpdate: Date.now(),
    color: "navy",
    isStarred: false,
    company: "React",
    domain: "google.com",
    logo: "https://logo.clearbit.com/reactjs.org",
    jobTitle: "Software Engineer IV",
    applyDate: "2020-01-01",
    deadlineDate: "2020-11-22",
    status: STATUS.APPLIED,
    url: "",
    notes: "",
  },
];
